server:
  port: 8080
eureka:
  # 心跳检测检测与续约时间
  # 测试时将值设置设置小些，保证服务关闭后注册中心能及时踢出服务
  server:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: analysisProvider
  datasource:
    url: "jdbc:mysql://59.110.140.1:3306/test?useUnicode=true&characterEncoding=utf-8"
    username: test
    password: test_password
    driver-class-name: com.mysql.jdbc.Driver
    
mybatis:
  mapper-locations: 
    classpath:mapper/*.xml
  type-aliases-package: 
    com.viewhigh.analysis.eureka.provider.domain